Move the metric prefix string to a label
ethereum-optimism/optimism pull request #1047
Opened 2021-06-09 16:28 UTC by optimisticben

**Description**
Move the metric prefix string to a label

**Additional context**
Changing metric names with a prefix or suffix affects the ability to reuse metric queries. It would be better to keep consistent metric names for the same metrics and use labels to identify specific services.

2021-06-09 16:33 UTC, annieke requested changes
the change sounds good to me, would make `prefix` an optional parameter here to fix errors:
https://github.com/ethereum-optimism/optimism/blob/859437f9eb94665606d826b6eb1f66be13b4a545/packages/common-ts/src/common/metrics.ts#L11-L35

2021-06-09 16:34 UTC, annieke commented
also here's where to make the matching update in batch submitter:
https://github.com/ethereum-optimism/optimism/blob/859437f9eb94665606d826b6eb1f66be13b4a545/packages/batch-submitter/src/exec/run-batch-submitter.ts#L179-L183

2021-06-09 16:34 UTC, tynes commented
Could you add a changeset with the command `yarn changeset` and then use the spacebar to select the modified package and commit the changeset file

2021-06-09 19:44 UTC, optimisticben commented
Updated based on the comments 🙏

2021-06-09 23:07 UTC, annieke approved these changes

2021-06-10 23:24 UTC, tynes requested changes
Do you mind updating the `changeset` to have `patch` changes? Since we are still major version 0, we are saving the `minor` version for the next regenesis

2021-06-11 15:01 UTC, optimisticben commented
> Do you mind updating the `changeset` to have `patch` changes? Since we are still major version 0, we are saving the `minor` version for the next regenesis

Sure, updated!

2021-06-11 23:44 UTC, tynes submitted a review, later dismissed

2021-06-11 23:45 UTC, tynes commented
This should be fine to merge, the failing test is a known issue

2021-06-14 22:10 UTC, tynes commented
If this is rebased on `develop` then it should pass all tests

2021-06-17 15:38 UTC, tynes approved these changes

2021-06-17 15:38 UTC, merged