dispute-game: Sanity check disputed claim index
ethereum-optimism/optimism pull request #10520
Opened 2024-05-13 17:04 UTC by Inphi

The `IFaultDisputeGame.move` interface has been modified to accept a disputed `Claim` hash. This allows the FDG to sanity check the disputed claim hash against its corresponding index in the `claimData` array.

This improves the UX of the interface to guard against possible reorgs when a challenger attempts to move against a reorg'd claim at an incorrect `claimData` index.

2024-05-13 18:02 UTC, clabby approved these changes
Change LGTM. Good to go pending challenger changes.

2024-05-13 19:20 UTC, clabby requested changes
Needs CTB snapshots

2024-05-13 20:52 UTC, ajsutton commented on packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol
> +    function move(Claim _disputed, uint256 _challengeIndex, Claim _claim, bool _isAttack) public payable virtual {
The params in the method comment haven't been updated.

2024-05-14 00:13 UTC, ajsutton approved these changes

2024-05-14 16:19 UTC, clabby approved these changes

2024-05-14 16:40 UTC, merged