Feat proxyd consensus backup
ethereum-optimism/optimism pull request #10668
Opened 2024-05-28 16:53 UTC by jelias2

**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

2024-05-28 23:35 UTC, felipe-op commented on proxyd/backend.go
> +	FallbackBackends []string
Let's just create a map[string]bool for quick lookup

2024-06-03 23:00 UTC, felipe-op requested changes

2024-06-03 23:00 UTC, felipe-op commented on proxyd/consensus_poller.go
> +	log.Info("Number of primary canidates", ":", len(ah.cp.backendGroup.Primaries()))
nit: candidates

let's use structured logs instead of concatenating strings

2024-06-03 23:00 UTC, felipe-op commented on proxyd/consensus_poller.go
> +				log.Info("Number of healthy primary canidates", ":", len(healthyCandidates))
ditto

2024-06-03 23:00 UTC, felipe-op commented on proxyd/consensus_poller.go
> +					log.Info("Zero healthy candidates, querying fallback backend",
nit: log messages in lower case

2024-06-03 23:00 UTC, felipe-op commented on proxyd/integration_tests/fallback_test.go
> +		// 	require.NotContains(t, consensusGroup, nodes["fallback"].backend)
remove commented code

2024-06-03 23:00 UTC, felipe-op commented on proxyd/integration_tests/testdata/fallback.toml
> +fallback = true
does this still have any effect?
I thought we would declare the fallbacks within the backend group instead

2024-06-03 23:00 UTC, felipe-op commented on proxyd/integration_tests/testdata/fallback.toml
> +fallback = true
we should just declare the fallbacks as a list of strings
i.e.

```
backends = ["normal", "normal2"]
fallbacks ["fallback", "fb2"]
```

2024-06-03 23:00 UTC, felipe-op commented on proxyd/config.go
> +	FallbackBackends map[string]bool `toml:"fallbacks"`
can we just have a simple []string to declare the fallbacks?

2024-06-03 23:00 UTC, felipe-op commented on proxyd/proxyd.go
> +					log.Crit("Error Backend Not Found in Backend Fallback Configurations", "Fallback Name", be)
lower case logging
"Fallback Name" should be "fallback_name" so we can to structured log search

2024-06-03 23:00 UTC, felipe-op commented on proxyd/proxyd.go
> +					log.Debug("Configuring new backend for group", "Group", bgName, "Backend", be, "fallback", fallback)
ditto

2024-06-03 23:14 UTC, jelias2 commented on proxyd/integration_tests/testdata/fallback.toml
> +fallback = true
correct, this is no longer required in the config, it will be removed

2024-06-03 23:16 UTC, jelias2 commented on proxyd/integration_tests/testdata/fallback.toml
> +fallback = true
Sure, I will update it.

I interpreted [this](https://github.com/ethereum-optimism/optimism/pull/10668#discussion_r1617994110) comment as the bool string lookup within the config and memory, but I can update the config to the new format

2024-06-03 23:17 UTC, jelias2 commented on proxyd/config.go
> +	FallbackBackends map[string]bool `toml:"fallbacks"`
Sure I will update

2024-06-04 00:29 UTC, felipe-op commented on proxyd/integration_tests/testdata/fallback.toml
> +fallback = true
the []string is to model the config, which you'll use then to create the map[string]bool for an efficient lookup

2024-06-04 22:20 UTC, felipe-op approved these changes

2024-06-04 22:59 UTC, jelias2 commented
Squashing commits before merging

2024-06-04 23:37 UTC, merged