op-batcher: log oldest l1 origin when channel close
ethereum-optimism/optimism pull request #10676
Opened 2024-05-29 13:18 UTC by zhiqiangxu

Currently when channel closes, only the latest l1 origin is logged.

It may be helpful to also output the oldest l1 origin in channel, e.g., when reasoning why `close to sequencer window timeout` is happening more often than expected sometimes.

2024-06-04 19:51 UTC, sebastianst requested changes
This is a nice addition to the channel closing logs, thanks!

Would be great to also add a unit test for this, covering the different cases. Even though the new fields are only used in logs for now, this might change in the future.

2024-06-04 19:51 UTC, sebastianst commented on op-batcher/batcher/channel_builder.go
> +		}
```suggestion
		c.latestL2 = eth.ToBlockID(block)
```

2024-06-04 19:51 UTC, sebastianst commented on op-batcher/batcher/channel_builder.go
> +		}
```suggestion
		c.oldestL2 = eth.ToBlockID(block)
```

2024-06-04 23:30 UTC, zhiqiangxu commented
> This is a nice addition to the channel closing logs, thanks!
> 
> Would be great to also add a unit test for this, covering the different cases. Even though the new fields are only used in logs for now, this might change in the future.

@sebastianst Thanks for suggesting using `ToBlockID`, that's cleaner:)

The logic for the added 3 fields is quite similar to the existing `ChannelBuilder.latestL1Origin` field, and there seems to be no test for `ChannelBuilder.latestL1Origin`? So I'm a bit out of mind of what to test.

2024-06-10 19:38 UTC, sebastianst commented
> > This is a nice addition to the channel closing logs, thanks!
> > Would be great to also add a unit test for this, covering the different cases. Even though the new fields are only used in logs for now, this might change in the future.
> 
> @sebastianst Thanks for suggesting using `ToBlockID`, that's cleaner:)
> 
> The logic for the added 3 fields is quite similar to the existing `ChannelBuilder.latestL1Origin` field, and there seems to be no test for `ChannelBuilder.latestL1Origin`? So I'm a bit out of mind of what to test.

@zhiqiangxu The latest l1 origin is implicitly accessed in other tests. The new fields aren't. I'm thinking of a simple test where, say 3, dummy blocks are added and then assertions made about the oldest and latest L1 origin and L2 are made.

2024-06-11 02:27 UTC, zhiqiangxu commented
> > > This is a nice addition to the channel closing logs, thanks!
> > > Would be great to also add a unit test for this, covering the different cases. Even though the new fields are only used in logs for now, this might change in the future.
> > 
> > 
> > @sebastianst Thanks for suggesting using `ToBlockID`, that's cleaner:)
> > The logic for the added 3 fields is quite similar to the existing `ChannelBuilder.latestL1Origin` field, and there seems to be no test for `ChannelBuilder.latestL1Origin`? So I'm a bit out of mind of what to test.
> 
> @zhiqiangxu The latest l1 origin is implicitly accessed in other tests. The new fields aren't. I'm thinking of a simple test where, say 3, dummy blocks are added and then assertions made about the oldest and latest L1 origin and L2.

Hi @sebastianst , I found there was an existing testcase `TestChannelBuilder_LatestL1Origin`, and I followed its style to test for the 3 new fields. Pls take a look:)

2024-06-11 21:02 UTC, sebastianst approved these changes
Thanks!

2024-06-11 21:22 UTC, merged