op-batcher/op-proposer: Only pass lifecycle contexts into RollupProvider.RollupClient
ethereum-optimism/optimism pull request #10705
Opened 2024-05-31 19:04 UTC by BrianBland

**Description**

Ensures that only lifecycle contexts are passed into `RollupProvider.RollupClient` in order to provide sufficient time for endpoint failover.

If a deadlined context is passed in, a single unresponsive host could singlehandedly consume the entire context deadline due to long timeouts and/or retries, causing each call to RollupClient to repeatedly fail when querying this host. With this change, the `RollupProvider`'s own network deadlines will be utilized, which in active failover mode may consume up to `2 * NumURLs * NetworkTimeout` time, or `NumURLs * 2 minutes` with present configurations.

**Tests**

No tests added, as this simply modifies the contexts passed into existing code.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

2024-05-31 23:46 UTC, BrianBland commented
cc @sebastianst

2024-06-04 13:10 UTC, sebastianst requested changes

2024-06-04 13:10 UTC, sebastianst commented on op-batcher/batcher/driver.go
> +	syncStatus, err := rollupClient.SyncStatus(cCtx)
The same has to be done above in `loadBlockIntoState` for `l.EndpointProvider.EthClient(ctx)`. Please also check if there are any other calls to `l.EndpointProvider.EthClient(ctx)` where the timeout has to be removed from the context.

2024-06-04 13:10 UTC, sebastianst commented on op-service/dial/static_rollup_provider.go
> +	// specifically in the case of failover.
```suggestion
	// Note: ctx should be a lifecycle context without an attached timeout as client selection may involve multiple network operations,
	// specifically in the case of failover.
```

2024-06-04 13:10 UTC, sebastianst commented on op-service/dial/static_rollup_provider.go
> +	// Note: ctx should be a lifecycle context as client selection may involve multiple network operations,
Please add the same note to the `EthClient` function of the `L2EndpointProvider` interface.

2024-06-04 17:20 UTC, BrianBland commented on op-batcher/batcher/driver.go
> +	syncStatus, err := rollupClient.SyncStatus(cCtx)
This appears to be the only location where `l.EndpointProvider.EthClient(ctx)` is called, and the only calling chain directly passes in `l.shutdownCtx` as the context

2024-06-04 19:28 UTC, sebastianst approved these changes

2024-06-04 19:47 UTC, merged