maintenance[contracts]: remove onlyRelayer modifier
ethereum-optimism/optimism pull request #1097
Opened 2021-06-15 19:10 UTC by smartcontracts

**Description**
Removes the `onlyRelayer` modifier which should no longer be used in the system since users will now be able to relay their own withdrawals. Also removes references to the modifier and to the `OVM_L2MessageRelayer` address elsewhere.

2021-06-15 23:54 UTC, maurelian approved these changes

2021-06-17 15:36 UTC, tynes commented
Note that this will remove the ability to pause withdrawals in the case of a hack. This should definitely be merged at some point in the future, we just need to decided on when. `regenesis/0.4.0` has been feature frozen, so this should become based on `regenesis/0.5.0` and then we can decide if we feel safe not having a switch to pause withdrawals by then

2021-06-17 15:37 UTC, tynes requested changes
Please base on `regenesis/0.5.0`

2021-06-29 13:46 UTC, snario approved these changes

2021-06-29 13:59 UTC, ben-chain approved these changes
LGTM!

2021-06-29 15:26 UTC, merged