op-chain-ops: Fix the wrong variable in 'checkUpgradeTxs'
ethereum-optimism/optimism pull request #11001
Opened 2024-06-25 09:15 UTC by CarolAHHaydn

1. The 'activBlock' variable is misspelled in function 'checkUpgradeTxs'.
2. Fix other misspelled in op-chain-ops

2024-06-28 05:51 UTC, CarolAHHaydn commented
PLZ have a review @protolambda

2024-06-28 23:01 UTC, protolambda requested changes

2024-06-28 23:01 UTC, protolambda commented on op-chain-ops/genesis/config.go
> +			return fmt.Errorf("%w: DACommitmentType must be either KeccakCommitments or GenericCommitment", ErrInvalidDeployConfig)
```suggestion
			return fmt.Errorf("%w: DACommitmentType must be either KeccakCommitment or GenericCommitment", ErrInvalidDeployConfig)
```

2024-06-28 23:01 UTC, protolambda commented on op-chain-ops/genesis/testdata/test-deploy-config-full.json
> +  "daCommitmentType": "KeccakCommitments",
```suggestion
  "daCommitmentType": "KeccakCommitment",
```

2024-06-29 18:17 UTC, protolambda approved these changes

2024-06-29 18:36 UTC, merged