fix(contracts): prevent L2->L1 calls to system contracts
ethereum-optimism/optimism pull request #1183
Opened 2021-06-28 18:57 UTC by maurelian

Description

A small change to the L1 Messenger, which prevents an L2 to L1 call from send calling the CTC.

2021-06-28 19:03 UTC, tynes commented
I've confirmed that the mainnet artifact is as expected. This will need to follow up with a `yarn generate-markdown` to create the `deployments/README.md` with the updated address

2021-06-28 19:14 UTC, ben-chain approved these changes
LGTM! 👍

2021-06-28 19:40 UTC, smartcontracts submitted a review, later dismissed

2021-06-28 22:14 UTC, tynes requested changes
Still needs to run `yarn generate-markdown`

2021-06-28 23:47 UTC, maurelian commented on packages/contracts/deployments/README.md
> +| Proxy__OVM_L1ETHGateway               | [0xA721CF3e39E5cB4CfEEc0e32EE05B3D05AA9aE39](https://goerli.etherscan.io/address/0xA721CF3e39E5cB4CfEEc0e32EE05B3D05AA9aE39) |
This also changed when I ran the script. 
It looks like the [artifact](https://github.com/ethereum-optimism/optimism/pull/603/files?file-filters%5B%5D=.json&file-filters%5B%5D=.md#diff-5b6fb2aa87259920aaf22a127f8dcfd4064c87f1093aa888ae54357194a02977) was added in #603, but the README [wasn't updated](https://github.com/ethereum-optimism/optimism/pull/603/files?file-filters%5B%5D=.json&file-filters%5B%5D=.md#diff-29c13e9d05968171f1b77293799876fe6afc393f674123ee883d49c50f25a14e) in the PR.

2021-06-28 23:52 UTC, maurelian commented on packages/contracts/deployments/README.md
> -OVM_L1StandardBridge:
I'm trying to figure out why this disappeared.

2021-06-29 13:56 UTC, maurelian commented
> Still needs to run `yarn generate-markdown` to create the `packages/contracts/README.md`

Done. This change only affected the impl addresses, which only affects an html comment, so the tables themselves were unaffected.

2021-06-29 19:05 UTC, maurelian commented on packages/contracts/deployments/README.md
> + - https://kovan.etherscan.io/address/0x333d2674E2D7e1e7327dc076030ce9615183709C)
After running `yarn generate-markdown` the only changes were in these comments, because the only deployed changes are to implementation contracts.

2021-06-29 19:45 UTC, tynes approved these changes

2021-06-29 21:52 UTC, merged