make default game type the same as `standard.DisputeGameType`
ethereum-optimism/optimism pull request #13028
Opened 2024-11-22 05:19 UTC by zhiqiangxu

The default game type deployed by op-deployer is `1`, but the default game type of op-proposer is `0`, if the user start op-proposer without specifying game-type, he'll get such error:

```
t=2024-11-22T01:48:46+0000 lvl=error msg="Failed to send proposal transaction" err="failed to create the tx: operation failed permanently after 30 attempts: failed to estimate gas: execution reverted, reason: 0x031c6de40000000000000000000000000000000000000000000000000000000000000000" l1blocknum=7126333 l1blockhash=0xf254e1207242ccbfd849b1d6e0bbe29d03cdc406b7d22a7e31bbd48e83e2b016 l1head=7126337
```
which is very confusing to new users.

This PR makes the default game type of op-proposer be the same as the default of op-deployer.

2024-11-24 20:58 UTC, ajsutton requested changes
This is a pretty significant backwards incompatible change that would cause liveness failures on chains using the default game type.

With the aim to get chains to stage 1, that will mean moving them all to permissionless games. While it currently makes sense for op-deployer to default to permissioned (for a bunch of reasons) that won't be true long term so I don't think we should break op-proposer backward compatibilty in this way since we expect 0 to be the right value long term..

2024-11-26 01:57 UTC, zhiqiangxu commented
@ajsutton Thanks for the feedback and sorry for the delay! I've just got some time to look into it. I've a quick question though: does it hold that the game type of op-proposer should always be the same as `OptimismPortal2.respectedGameType`? I'm thinking of adding a check to the op-proposer and log some useful tips when supplied game type isn't the expected game type.

2024-11-26 02:32 UTC, ajsutton commented
> @ajsutton Thanks for the feedback and sorry for the delay! I've just got some time to look into it. I've a quick question though: does it hold that the game type of op-proposer should always be the same as `OptimismPortal2.respectedGameType`? I'm thinking of adding a check to the op-proposer and output some useful tips when supplied game type isn't the expected game type.

That's not necessarily a requirement though it is typical. I don't think it would be worth adding extra complexity to make op-proposer monitor the respectedGameType just to log information about this.

2024-11-26 02:34 UTC, zhiqiangxu commented
> > @ajsutton Thanks for the feedback and sorry for the delay! I've just got some time to look into it. I've a quick question though: does it hold that the game type of op-proposer should always be the same as `OptimismPortal2.respectedGameType`? I'm thinking of adding a check to the op-proposer and output some useful tips when supplied game type isn't the expected game type.
> 
> That's not necessarily a requirement though it is typical. I don't think it would be worth adding extra complexity to make op-proposer monitor the respectedGameType just to log information about this.

What's your suggested change?

2024-11-26 02:37 UTC, ajsutton commented
I don't believe a change is required here. Maybe there's some documentation somewhere that needs updating but I'm not sure what docs you were following.

2024-11-26 02:39 UTC, zhiqiangxu commented
> I don't believe a change is required here. Maybe there's some documentation somewhere that needs updating but I'm not sure what docs you were following.

I'm also inclined to leave it as is, I was following this document: https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#start-op-proposer

2024-11-26 02:44 UTC, closed without merging