Add hardhat task for withdrawing ETH fees
ethereum-optimism/optimism pull request #1316
Opened 2021-08-05 19:04 UTC by K-Ho

**Description**
Adds a hardhat task to withdraw our ETH fees to L1

2021-08-05 19:17 UTC, tynes commented on packages/contracts/README.md
> +  --contracts-rpc-url https://mainnet.optimism.i \
There is a typo on this line

2021-08-05 19:18 UTC, tynes commented on packages/contracts/README.md
> +  --use-ledger true \  # `network` MUST equal your env var `CONTRACTS_TARGET_NETWORK`
I didn't set the `CONTRACTS_TARGET_NETWORK` and was able to run this without a problem

2021-08-05 19:18 UTC, tynes commented on packages/contracts/README.md
> +  --private-key 0x... \  # The private key to withdraw fees with. Ensure this wallet has ETH on L2 to pay the tx fee.
nit: move comments out of the code snippet and above so that it is easier to copy/paste the command

2021-08-05 19:20 UTC, tynes commented on packages/contracts/tasks/withdraw-fees.ts
> +      await l2FeeVault.estimateGas.withdraw()
Should this log the result of the gas estimation? Should it be an `eth_call`?

2021-08-05 19:21 UTC, tynes commented
Not sure why the linter doesn't catch the things locally that github displays in the UI

2021-08-05 19:21 UTC, tynes requested changes
Could use a changeset

2021-08-05 19:50 UTC, tynes commented
Will approve if you squash into a single commit

2021-08-06 18:56 UTC, K-Ho commented
> Could use a changeset

added and squashed + rebased

2021-08-06 19:48 UTC, tynes approved these changes

2021-08-06 22:14 UTC, merged