feat: revamp contracts folder structure
ethereum-optimism/optimism pull request #13230
Opened 2024-12-04 19:29 UTC by smartcontracts

Long time coming, this commit revamps the folder structure for all contracts so that the logical role of each contract is more immediately obvious.

2024-12-04 20:28 UTC, JosepBove commented
Looks perfect to me

2024-12-04 21:56 UTC, ControlCplusControlV commented
No comments either, really well done

2024-12-05 00:28 UTC, tynes requested changes
Please do not merge this until std L2 genesis is merged. This is going to create a rebasing nightmare and reduce the effectiveness of the audit

2025-02-20 16:45 UTC, opgitgovernance commented
This pr has been automatically marked as stale and will be closed in 5 days if no updates

2025-02-24 21:40 UTC, closed without merging