chore(contracts): defaults lib w/ address, unit256
ethereum-optimism/optimism pull request #1442
Opened 2021-09-11 20:27 UTC by davisshaver

**Description**
Adds default values library for default address and uint256.

**Additional context**
n/a

**Metadata**
- Fixes #803

2021-09-12 04:43 UTC, smartcontracts requested changes
Thanks for the PR! Requesting a few minor changes but glad someone is taking up this issue :-)

2021-09-12 04:43 UTC, smartcontracts commented on packages/contracts/contracts/optimistic-ethereum/libraries/utils/Lib_DefaultValues.sol
> +  address public constant DEFAULT_ADDRESS = 0xE0f5206BBD039e7b0592d8918820024e2a7437b9;
Address here should be `0xdEfa017defA017DeFA017DEfa017DeFA017DeFa0`

2021-09-12 04:43 UTC, smartcontracts commented on packages/contracts/contracts/optimistic-ethereum/libraries/utils/Lib_DefaultValues.sol
> +// SPDX-License-Identifier: MIT
Could you actually move this file into the `/constants` folder?

2021-09-12 04:43 UTC, smartcontracts commented on packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
> +contract OVM_ExecutionManager is iOVM_ExecutionManager, Lib_AddressResolver, Lib_DefaultValues {
IMO instead of using `is Lib_DefaultValues` it would be better to do `Lib_DefaultValues.DEFAULT_ADDRESS`. It's a little more explicit.

2021-09-13 17:53 UTC, smartcontracts approved these changes
LGTM! Thank you!

2021-09-13 19:32 UTC, tynes commented
Are we sure that this is a non breaking change in the sense the bytecode will be 1:1? If no, this needs to target the experimental branch

2021-09-13 19:46 UTC, smartcontracts commented
Actually I need to dismiss my original approval. Since this PR changes contracts it is considered a breaking change and must therefore target the latest release branch (the `experimental` branch). However, these constant values may no longer exist within the `experimental` branch. I would recommend taking a look at that branch and checking if this PR would still apply there. If so, feel free to retarget that branch.

2021-09-13 20:45 UTC, closed without merging