feat: clean up deployment artifacts
ethereum-optimism/optimism pull request #1768
Opened 2021-11-14 17:05 UTC by smartcontracts

**Description**
Various deployment artifact cleanups:
1. Removed `mainnet-trial` and `mainnet-trial-2` artifacts.
2. Simplified the `generate-markdown.js` script slightly.
3. Added `AddressDictator` and `ChugSplashDictator` to the list of hidden addresses.

2021-11-16 05:00 UTC, maurelian requested changes

2021-11-17 06:21 UTC, smartcontracts commented on packages/contracts/deployments/goerli/README.md
> +<a href="undefined/address/0x4200000000000000000000000000000000000000">
Lol, whoops. Good catch.

2021-11-17 06:21 UTC, smartcontracts commented on packages/contracts/deployments/goerli/README.md
> +Optimistic Goerli is an internal Optimism development network. You're probably looking for [Optimistic Kovan](../kovan), the public Optimistic Ethereum testnet.
Great point.

2021-11-17 16:31 UTC, maurelian approved these changes
LGTM

2021-11-22 21:40 UTC, annieke approved these changes
checked the new deployment md files and they look good, `generate-markdown.ts` is also v easy to read so lgtm!

2021-11-22 21:40 UTC, annieke commented on packages/contracts/scripts/generate-markdown.ts
> +  // allows us to create a table where each column is 1/2 the full README width.
nice

2021-11-22 22:18 UTC, merged