packages/contracts: Remove legacy `bin/deploy.ts` script
ethereum-optimism/optimism pull request #1951
Opened 2021-12-21 06:34 UTC by mslipper

Removes the `bin/deploy.ts` script, which was a holdover from before the regenesis and was little more than a wrapper around `npx hardhat deploy`. The functionality that used to live in `bin/deploy.ts` has been moved into `ops/scripts/deployer.sh`, since the old script's functionality was exclusively run in CI.

Metadata:

- Fixes ENG-1447

2021-12-21 17:23 UTC, tynes commented on ops/docker/Dockerfile.deployer
> +CMD ./ops/scripts/deployer.sh
It should be fine to skip using `yarn` for the deployer, but other services may consume env vars injected into the runtime from `yarn`

2021-12-21 17:26 UTC, tynes commented on ops/scripts/deployer.sh
> +# First, create two files. One of them contains a list of addresses, the other contains a list of contract names.
Nice bash wizardry

2021-12-21 17:32 UTC, tynes approved these changes

2021-12-21 18:24 UTC, smartcontracts approved these changes
Nice, been wanting this removed for a while.

2021-12-22 00:45 UTC, tynes requested changes
Just realized this should have a changeset for the contracts so it versions the deployer docker image

2021-12-22 04:32 UTC, tynes approved these changes

2021-12-22 16:21 UTC, merged