Split OVMMulticall.sol into Multicall.sol & OVMContext.sol in integration tests
ethereum-optimism/optimism pull request #2024
Opened 2022-01-17 16:04 UTC by indeavr

**Changes in Contracts**

Deleted OVMMulticall.sol. 
(new) Multicall.sol --> copied from the [makerdao implementation](https://github.com/makerdao/multicall/blob/master/src/Multicall.sol)
(new) OVMContext.sol --> contains the helper functions.
OVMContextState.sol --> extends from OVMContext.sol.

#### Changes in tests:
1. All `aggregate()` invocations now call Multicall.sol
2. OVMContextState.sol is now used for calling the helper functions. 

**Metadata**
- Fixes [#2014](https://github.com/ethereum-optimism/optimism/issues/2014)

2022-01-18 19:55 UTC, tynes commented on integration-tests/test/ovmcontext.spec.ts
> +describe.only('OVM Context: Layer 2 EVM Context', () => {
Do you mind removing this `only`?

2022-01-18 19:57 UTC, tynes requested changes
Will re-review when the comment is addressed, please be sure to squash into a single clean commit :)

2022-01-18 19:57 UTC, tynes commented
If you could also add a changeset for the integration tests, that would be appreciated

2022-01-18 21:39 UTC, smartcontracts commented
Great work as always @indeavr! Just needs another rebase and should be good to go. Not sure if you've already reached out, but feel free to email me an ETH address to [kelvin AT optimism DOT io] if you would like a contributor NFT :-)

2022-01-20 00:40 UTC, tynes approved these changes

2022-01-20 00:42 UTC, merged