l2geth: fix log.Crit usage
ethereum-optimism/optimism pull request #2495
Opened 2022-04-23 06:22 UTC by modagi

fix log.Crit usage
```
log.Crit("Sequencer cannot sync transactions to tip: %w", err)
log.Crit("Sequencer cannot sync queue to tip: %w", err)
```

->

```
log.Crit("Sequencer cannot sync transactions to tip", "err", err)
log.Crit("Sequencer cannot sync queue to tip", "err", err)
```

2022-04-23 12:28 UTC, tynes requested changes

2022-04-23 12:28 UTC, tynes commented on .changeset/new-hairs-scream.md
> +'@eth-optimism/l2geth': minor
Could you make this a patch release?

2022-04-23 12:56 UTC, modagi commented on .changeset/new-hairs-scream.md
> +'@eth-optimism/l2geth': minor
okay. just changed.

2022-04-24 12:05 UTC, mslipper approved these changes

2022-04-24 16:10 UTC, tynes approved these changes

2022-04-24 16:22 UTC, merged