fix(ctp): re-deploy RetroReceiver with new owner
ethereum-optimism/optimism pull request #2683
Opened 2022-06-04 17:11 UTC by smartcontracts

**Description**
Re-deploys the RetroReceiver with a new default owner called the
Dedicated Deterministic Deployer address. When deploying authenticated
smart contracts deterministically to the same address on many chains,
it's necessary to have a known static owner that then transfers
ownership to the final owner after deployment (which can be different on
every chain). This PR re-deploys the original contract with that new
default owner, the DDD.

2022-06-07 20:37 UTC, tynes requested changes
The `deployments` directory is in the npm package, this should get a changeset

2022-06-07 20:50 UTC, smartcontracts commented
> The `deployments` directory is in the npm package, this should get a changeset

Done

2022-06-07 21:13 UTC, tynes approved these changes

2022-06-08 19:44 UTC, tynes approved these changes

2022-06-08 20:19 UTC, merged