feat(dev-env): Pin yarn version
ethereum-optimism/optimism pull request #2806
Opened 2022-06-16 22:00 UTC by roninjin10

Yarn is a small (or at least smaller than you'd expect) javascript file.  Committing it in the monorepo guarantees that anybody using the monorepo is all using the latest and consistent version of yarn.  Run `yarn update:yarn` to update the version.

This matches what we did in gateway in this pr https://github.com/ethereum-optimism/gateway/pull/417

2022-06-16 22:00 UTC, roninjin10 commented
Messed up git commits completely fixing

2022-06-16 22:02 UTC, mslipper requested changes

2022-06-16 22:02 UTC, mslipper commented on packages/common-ts/src/base-service/base-service-v2.ts
> -export type MetricsV2 = {
Did you mean to include this?

2022-06-16 22:02 UTC, mslipper commented on .changeset/clever-bees-visit.md
> +'@eth-optimism/common-ts': minor
Did you mean to include this?

2022-06-16 22:14 UTC, roninjin10 commented
@mslipper i messed up my git but fixed.   

Seperately, I included a changeset that minor bumps every package but that seems odd since I technically changed 0 packages here.

2022-06-16 22:23 UTC, mslipper commented
You don't need that changeset - the Mergify comment is just a reminder 😄

2022-06-17 22:27 UTC, tynes approved these changes

2022-06-21 17:11 UTC, mslipper approved these changes

2022-06-21 17:30 UTC, merged