Add sequencer role to oracle
ethereum-optimism/optimism pull request #2810
Opened 2022-06-17 16:36 UTC by maurelian

**Description**

Introduces a new role, so that the OutputOracle now has the following: 

- `owner` which can:
  - delete outputs
  - change the sequencer's address
  - transfer ownership

- `sequencer` which can:
	- append new outputs 	
 	

**Metadata**
- Fixes ENG-2255

2022-06-17 22:26 UTC, tynes commented on packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol
> +        sequencer = newSequencer;
This should emit an event

2022-06-17 22:26 UTC, tynes commented on packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol
> +    ) external payable onlySequencer {
We should have a tool that we can mount the key into an image and run to delete outputs. Not a blocker for this PR but logistically if the same key used to submit batches is used to delete outputs we need to be logistically ready. hh tasks require a non significant amount of memory which isn't ideal but it is a standard way to do so, otherside a bash script that uses cast

2022-06-21 15:25 UTC, tynes commented on packages/contracts-bedrock/contracts/test/L2OutputOracle.t.sol
> +
I see these are still todos

2022-06-21 15:25 UTC, tynes commented on packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol
> +     * @notice Emitted when the sequencer address is changed.
This needs `@param`s in the natspec

2022-06-21 15:27 UTC, tynes commented
Generally looks good to me, looks like the go bindings are out of date which is causing the CI to fail

2022-06-21 17:00 UTC, maurelian commented
@tynes:
> We could add something to CI that warns on storage slot changes too if we want to

This is a good idea. WDYT of this approach?
1. Create a directory in the bedrock package called `.layouts`
2. Create a file for each relevant contract in that directory (ie. `.layouts/OptimismPortal`)
2. Create simple bash script that runs `forge inspect <ContractName> storage-layout .layouts/<ContractName>` 
3. Fail if the file git diff on the file is non-empty

2022-06-21 17:07 UTC, tynes commented
> @tynes:
> 
> > We could add something to CI that warns on storage slot changes too if we want to
> 
> This is a good idea. WDYT of this approach?
> 
> 1. Create a directory in the bedrock package called `.layouts`
> 2. Create a file for each relevant contract in that directory (ie. `.layouts/OptimismPortal`)
> 3. Create simple bash script that runs `forge inspect <ContractName> storage-layout .layouts/<ContractName>`
> 4. Fail if `git diff` on the file is non-empty

See https://github.com/foundry-rs/foundry/issues/2056

2022-06-22 17:25 UTC, tuxcanfly reviewed
Running `forge test` I'm seeing a test failure. Tried rebuilding from scratch too. Weird since CI seems to pass.

`[FAIL. Reason: OutputOracle: Blockhash does not match the hash at the expected height.] test_appendWithBlockhashAndHeight() (gas: 20419)
`

2022-06-22 17:27 UTC, maurelian commented
Odd, I can't repro that.
@tuxcanfly what if you try `forge test --force` to recompile the contracts?

2022-06-22 17:28 UTC, tuxcanfly commented
Same.

2022-06-22 17:30 UTC, maurelian commented
oh.. updating forge does indeed break it for me too... :/

2022-06-22 18:01 UTC, Nicca42 requested changes

2022-06-22 18:01 UTC, Nicca42 commented on packages/contracts-bedrock/contracts/test/L2OutputOracle.t.sol
Delete tests should be split into happy and sad path like the Append tests.

2022-06-22 19:13 UTC, maurelian commented on packages/contracts-bedrock/contracts/test/L2OutputOracle.t.sol
> +    event SequencerChanged(address indexed, address indexed);
For the sake of testing this is fine.

2022-06-22 19:19 UTC, maurelian commented on packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol
> +        require(
Yeah... https://github.com/ethereum-optimism/optimism/pull/2810#discussion_r904042397

But I agree, allowing a no-op is fine. I'll remove it.

2022-06-22 19:28 UTC, maurelian commented on packages/contracts-bedrock/contracts/test/L2OutputOracle.t.sol
>      }
good catch

2022-06-22 19:28 UTC, maurelian commented on packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol
> +        emit SequencerChanged(sequencer, newSequencer);
done

2022-06-22 19:29 UTC, maurelian commented on packages/contracts-bedrock/contracts/test/L2OutputOracle.t.sol
> +    event SequencerChanged(address indexed, address indexed);
but I changed it anyways.

2022-06-22 19:31 UTC, tynes approved these changes

2022-06-22 20:55 UTC, merged