ops: use nightly foundry
ethereum-optimism/optimism pull request #2894
Opened 2022-06-29 17:22 UTC by tynes

**Description**
Uses `foundry:nightly` for the build

2022-06-29 17:26 UTC, mslipper requested changes
I'm concerned about using a nightly build in something that produces production code. Can we pick a version of the Foundry image, and retag it on our Docker Hub repo so that we can control changes?

2022-06-29 19:12 UTC, maurelian approved these changes

2022-06-29 22:51 UTC, tynes commented
> I'm concerned about using a nightly build in something that produces production code. Can we pick a version of the Foundry image, and retag it on our Docker Hub repo so that we can control changes?

Thats a good call, there is one change that we need that hasn't been merged into foundry yet, we can pin once that change gets in. The ethers-rs dep needs to be updated in foundry and then we need to make sure it fixes the problem we were seeing with the hh oom

2022-06-30 15:42 UTC, tynes commented
Will update this PR once the version of foundry is live that has the features we need

2022-07-06 23:33 UTC, closed without merging