op-node: Use unmetered L1 Attributes Transaction
ethereum-optimism/optimism pull request #3157
Opened 2022-08-02 15:20 UTC by trianglesphere

**Description**
Uses the new unmetered system transactions API for the L1 Info Transaction.
Relies on https://github.com/ethereum-optimism/reference-optimistic-geth/pull/36

**Additional context**
Devnet will be broken until the Geth PR is merged into `optimism-prototype` and the `latest`
tag is updated. This PR will also update the go modules when the above PR is merged.

2022-08-02 20:23 UTC, protolambda requested changes
Can you update the specs?

deposits doc needs the system tx format bool: https://github.com/ethereum-optimism/optimism/blob/develop/specs/deposits.md

and derivation doc needs to set it to true for block info, false for user deposits: https://github.com/ethereum-optimism/optimism/blob/develop/specs/derivation.md

2022-08-02 20:34 UTC, protolambda commented on specs/deposits.md
> +8. `isSystemTransaction` is set by the rollup node for certain transactions that have unmetered execution.
Can you make it more explicit it's `false` for user-deposited transactions?

2022-08-02 20:43 UTC, trianglesphere commented on specs/deposits.md
> +8. `isSystemTransaction` is set by the rollup node for certain transactions that have unmetered execution.
```suggestion
8. `isSystemTransaction` is set by the rollup node for certain transactions that have unmetered execution.
  It is `false` for user deposited transactions
```

2022-08-02 20:59 UTC, protolambda approved these changes
need to rerun CI, op-e2e seems to have failed to start / output anything.

2022-08-03 04:34 UTC, mslipper approved these changes

2022-08-03 04:35 UTC, mslipper requested changes
CI is flagging a real bug, so requesting change until we fix it.

2022-08-03 04:42 UTC, protolambda commented
Ah, I think this breaks the deposit hash calculation in TS (used in devnet test), because of the new deposit systemTx field. 

The op-e2e timing out happens sometimes in CI though, I think that's unrelated.

2022-08-03 14:49 UTC, protolambda commented
The devnet `ethereumoptimism/reference-optimistic-geth:latest` image may still need to be updated. We switched from `optimism-prototype` to `optimism` branch as default in the reference-optimistic-geth repo. Both to keep the audit branch nice and stable, as well as to get rid of the `-prototype` suffix: it's not a prototype anymore, we're about to enter alpha public testnet.

2022-08-03 16:57 UTC, protolambda commented
Cancelled CI, `devnet` was running for 2h, we should add a timeout on that job. I think we just need to update the L2 reference geth docker image to point to the new branch that this PR introduces.

2022-08-03 18:27 UTC, protolambda commented
Geth repo nows builds docker images for the new default `optimism` branch, including the updates required for this PR. I don't think the devnet is using a specific docker tag, but just uses the latest, so other CI might temporarily break until we merge this in.

2022-08-03 18:38 UTC, tynes commented
We need to merge this because its breaking the devnet for other PRs

2022-08-03 18:41 UTC, protolambda commented
I think either the CI is running an older docker image, or my JS change is not good, I'm seeing this in CI logs:
```
Sending from 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
Depositing 1 ETH to 0xB79f76EF2c5F0286176833E7B2eEe103b1CC3244
0xB79f76EF2c5F0286176833E7B2eEe103b1CC3244 has 0.0 ETH on L2
Got TX hash 0x4b6f7e960d69276ef9c9a431e8acf27b8ced8a01a6b83bf8b61ec3f518a9e025. Waiting...
Included in block 0xc00acaa964fcdfa65490c20b2c92c6baeadcf28efdb710fd041e27403a26e102
Deposit has log index 1
Waiting for L2 TX hash 0x67251c1f210dd63a82eb58aaf2f0317f66bc72aec1a9fddd8b35834ab6b61743
Unexpected balance increase without detecting deposit transaction
latest block 211:0x7c59d94d829089088090d3acb3d64d4c4b839798eb2e441266ad84715766d50a
Unexpected balance increase without detecting deposit transaction
latest block 236:0x965047b4588d06a40b7c52f7d1682bc36c727ee02fdb3dd8a1b20de0fafe93d4
```
Which I think is because of the depsit-tx hash computation not matching between Go and JS. cc @tynes

2022-08-03 18:41 UTC, tynes commented on packages/core-utils/src/optimism/deposit-transaction.ts
I pulled the other helpers from ethers internal functions, there arent any for formatting bools so this looks good to me
https://github.com/ethers-io/ethers.js/blob/56fabe987bb8c1e4891fdf1e5d3fe8a4c0471751/packages/transactions/src.ts/index.ts#L118

2022-08-03 18:45 UTC, tynes commented
There are some solidity contracts that needs to be updated:
- https://github.com/ethereum-optimism/optimism/blob/bd65ee51a5ab592c53ef793e900e4add2924a8bc/packages/contracts-bedrock/contracts/libraries/Encoding.sol#L34
- https://github.com/ethereum-optimism/optimism/blob/bd65ee51a5ab592c53ef793e900e4add2924a8bc/packages/contracts-bedrock/contracts/libraries/Types.sol#L34

As well as the differential testing:
- https://github.com/ethereum-optimism/optimism/blob/bd65ee51a5ab592c53ef793e900e4add2924a8bc/packages/contracts-bedrock/scripts/differential-testing.ts#L87
- https://github.com/ethereum-optimism/optimism/blob/bd65ee51a5ab592c53ef793e900e4add2924a8bc/packages/contracts-bedrock/contracts/test/Hashing.t.sol#L126

2022-08-03 18:47 UTC, tynes commented
> I think either the CI is running an older docker image, or my JS change is not good, I'm seeing this in CI logs:
> 
> ```
> Sending from 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
> Depositing 1 ETH to 0xB79f76EF2c5F0286176833E7B2eEe103b1CC3244
> 0xB79f76EF2c5F0286176833E7B2eEe103b1CC3244 has 0.0 ETH on L2
> Got TX hash 0x4b6f7e960d69276ef9c9a431e8acf27b8ced8a01a6b83bf8b61ec3f518a9e025. Waiting...
> Included in block 0xc00acaa964fcdfa65490c20b2c92c6baeadcf28efdb710fd041e27403a26e102
> Deposit has log index 1
> Waiting for L2 TX hash 0x67251c1f210dd63a82eb58aaf2f0317f66bc72aec1a9fddd8b35834ab6b61743
> Unexpected balance increase without detecting deposit transaction
> latest block 211:0x7c59d94d829089088090d3acb3d64d4c4b839798eb2e441266ad84715766d50a
> Unexpected balance increase without detecting deposit transaction
> latest block 236:0x965047b4588d06a40b7c52f7d1682bc36c727ee02fdb3dd8a1b20de0fafe93d4
> ```
> 
> Which I think is because of the depsit-tx hash computation not matching between Go and JS. cc @tynes

This means the JS isn't computing the hash of the deposit tx correctly

2022-08-03 18:48 UTC, protolambda commented
Just checked the CI logs. Pulled down the exact docker image that is being used, and grepped the symbols in the geth binary to make sure it includes the latest updates, and it does. So it's some code in our testing that can't find the deposit correctly. Likely JS/solidity updates I missed.

2022-08-03 19:40 UTC, protolambda commented
Devnet stuck due to other PR, cancelled CI job because it didn't time out automatically (1h...)

2022-08-04 12:41 UTC, protolambda commented
Fixed a bug in deposit tx decoding (it was still skipping an extra byte, from when deposits had a version byte) + fixed encoding/decoding of the new boolean.

2022-08-04 16:36 UTC, mslipper approved these changes

2022-08-04 16:37 UTC, merged