fix(ctb): remove AddressManager from config
ethereum-optimism/optimism pull request #3854
Opened 2022-11-02 17:49 UTC by smartcontracts

**Description**
Removes AddressManager from deploy config, not necessary since we can just pull it from the deployments folder.

2022-11-02 21:57 UTC, tynes commented
For this to work on all networks, we will need to have this part of the hardhat config be updated for each network:
https://github.com/ethereum-optimism/optimism/blob/8fccc4334eb15c6d105e36680363eeef367ae5b0/packages/contracts-bedrock/hardhat.config.ts#L352

2022-11-02 21:57 UTC, tynes approved these changes

2022-11-02 23:37 UTC, tynes commented
Something is up with the newly merged mergify rules

```
Rule: Automatic merge on approval (queue) — Cannot use `speculative_checks` with queue action.
```

```
Cannot use `speculative_checks` with queue action.
warning The subscription needs to be updated to enable this feature.
```

2022-11-02 23:37 UTC, tynes requested changes
Could you add actual mainnet to the hh config for the hh deploy deployments entry? So we don't forget then

2022-11-03 02:27 UTC, smartcontracts commented
> Could you add actual mainnet to the hh config for the hh deploy deployments entry? So we don't forget then

Done

2022-11-03 17:41 UTC, tynes approved these changes

2022-11-03 17:57 UTC, merged