feat(dtl): fast goerli sync
ethereum-optimism/optimism pull request #4005
Opened 2022-11-15 17:03 UTC by smartcontracts

**Description**
Experimental release

2022-11-21 16:55 UTC, tynes commented
This change isn't particularly testable without syncing, can you confirm that this syncs without any issues?

2022-11-21 18:59 UTC, smartcontracts commented
@tynes Circle has synced a Goerli node using this change

2022-11-28 21:08 UTC, mslipper approved these changes

2022-12-02 20:06 UTC, zhwrd approved these changes

2022-12-02 20:56 UTC, smartcontracts commented
Needs review from @tynes

2022-12-02 22:49 UTC, zhwrd commented on packages/data-transport-layer/src/services/l1-ingestion/service.ts
> +      if (l1BlockRangeStart < 7260849) {
Getting an error when syncing past this block:

```
{"level":30,"time":1670021123131,"highestSyncedL1Block":7259320,"targetL1Block":7264320,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":40,"time":1670021123919,"message":"TransactionEnqueued: missing event: TransactionEnqueued","msg":"recovering from a missing event"}
```

2022-12-05 19:50 UTC, tynes requested changes
Needs a confirmation that this actually works before its merged

2022-12-05 23:39 UTC, zhwrd approved these changes
confirmed the changes work

2022-12-07 17:39 UTC, merged