feat(sdk): support legacy withdraws after Bedrock
ethereum-optimism/optimism pull request #4119
Opened 2022-11-30 21:59 UTC by smartcontracts

**Description**
Adds support for finalizing legacy withdrawals after the Bedrock migration. Cleans up some SDK code at the same time.

2022-11-30 22:09 UTC, tynes commented on packages/sdk/src/cross-chain-messenger.ts
> -    // Sanity check that the value is set to 1 in the state
Do you think this is a good sanity check? It would only break if we decided to start proving against a non bool in the state

2022-11-30 22:09 UTC, tynes commented on packages/sdk/src/cross-chain-messenger.ts
> -    const isMessageSent =
Do you think checking `isMessageSent` here is overkill?

2022-11-30 22:10 UTC, tynes commented on packages/sdk/src/cross-chain-messenger.ts
> -    const isMessageSent =
I feel like it'll give a better error message than something downstream

2022-11-30 22:10 UTC, tynes commented on packages/sdk/src/cross-chain-messenger.ts
> -    if (withdrawal.MessagePassed.withdrawalHash !== withdrawalHash) {
Slight preference to use the hash from the event instead of computing the hash client side, so that we can "just work" with protocol upgrades

2022-11-30 22:14 UTC, tynes approved these changes

2022-11-30 22:23 UTC, tynes commented
Looks like there is a problem in the codepath:

```
/home/circleci/project/packages/sdk/src/cross-chain-messenger.ts:419
      throw new Error(`can only convert L2 to L1 messages to low level`)
            ^
Error: can only convert L2 to L1 messages to low level
    at CrossChainMessenger.toLowLevelMessage (/home/circleci/project/packages/sdk/src/cross-chain-messenger.ts:419:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CrossChainMessenger.getMessageStatus (/home/circleci/project/packages/sdk/src/cross-chain-messenger.ts:695:30)
    at async Timeout._onTimeout (/home/circleci/project/packages/sdk/tasks/deposit-erc20.ts:319:29)
```

2022-11-30 22:23 UTC, tynes requested changes
test fail :(

2022-11-30 22:50 UTC, tynes commented on packages/sdk/src/cross-chain-messenger.ts
> +      if (withdrawals.length > 0) {
This should be `withdrawals.length > 1`

2022-11-30 22:51 UTC, tynes commented
Going to need to update this usage of `decodeVersionedNonce` as well: https://github.com/ethereum-optimism/optimism/blob/af9a5eed46cb45402c5894250c8688faaac691e9/packages/contracts-bedrock/scripts/differential-testing.ts#L25

2022-11-30 22:55 UTC, smartcontracts commented on packages/sdk/src/cross-chain-messenger.ts
> +      if (withdrawals.length > 0) {
oops

2022-12-01 20:36 UTC, mslipper approved these changes

2022-12-01 20:49 UTC, tynes approved these changes

2022-12-01 23:03 UTC, merged