feat(ci): Make build fail if lockfile changes
ethereum-optimism/optimism pull request #4481
Opened 2022-12-14 17:51 UTC by roninjin10

- --frozen-lockfile does not work on newer versions of yarn 1.x
- make a script copied from gateway repo that handles this

2022-12-14 17:51 UTC, roninjin10 commented
Current dependencies on/for this PR:
* develop
  * **PR #4481** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4481" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4481?utm_source=stack-comment).

2022-12-14 17:56 UTC, maurelian commented
Could we accomplish the same thing just by doing something like this instead? 

https://github.com/ethereum-optimism/optimism/blob/1cac435d49960f2f95f5bdde19350e84fe41c6ea/.circleci/config.yml#L756

2022-12-14 22:00 UTC, trianglesphere commented
Either the script or `git diff --exit-code` work. One question is why there's the extra really large checked in thing.

2022-12-14 22:28 UTC, smartcontracts commented
`yarn install && git diff --exit-code` might be easier

2022-12-14 22:37 UTC, trianglesphere requested changes
adding a reminder to not check in `.yarn/releases/yarn-1.22.19.cjs`

2022-12-15 03:00 UTC, roninjin10 commented
@trianglesphere not sure how that got into my git commits but will revert

2022-12-15 03:03 UTC, roninjin10 commented
@trianglesphere that file is the yarn runtime.    The way you upgrade yarn is you do `yarn set version 1.x` and it will update that file.   Would be a good idea to update it to latest but would rather do that in another pr

2022-12-15 03:14 UTC, roninjin10 commented
@trianglesphere @smartcontracts I finally remembered why I did it this way and not using git.  Because sometimes git doesn't exist.   You can be in a docker container without git for example.   Also what is more important than the script itself is the giant comment explaining why it exists.  I think the pr as is is best.

2022-12-15 03:17 UTC, roninjin10 commented
will change it though if anybody feels strongly

2022-12-15 03:19 UTC, roninjin10 commented
The docker issue I don't think is an issue for this repo.  It was for us when I implemented https://github.com/ethereum-optimism/gateway/pull/485

2022-12-15 03:25 UTC, roninjin10 commented
Looks like I copied this off internet from here https://github.com/yarnpkg/yarn/issues/5840#issuecomment-468782288 .  I was wondering why I wrote a bash script instead of a node script.

2022-12-15 23:52 UTC, roninjin10 commented
my bad closed pr thinking another pr merged accomplishing this

2022-12-16 01:52 UTC, trianglesphere commented
> If ya'll go with the using git strategy, I'd recommend doing it as a CI check instead of making git a necessary dependency of the overall build pipeline.

git's already installed on most of the executors/docker images that we use. First step is usually to do a checkout

2022-12-16 05:22 UTC, roninjin10 commented on packages/contracts-periphery/package.json
> +    "install:ci": "./scripts/yarn-lock-file.sh",
```suggestion
    "postinstall": "git diff --exit-code",
```

2022-12-16 05:26 UTC, roninjin10 commented
going to close for now I won't have time to really do anything here.  This is just a copy paste from gateway repo was only reason I was able to squeeze this pr.

2022-12-16 05:26 UTC, closed without merging