feat: add view modifiers to view functions
ethereum-optimism/optimism pull request #4709
Opened 2023-01-13 01:10 UTC by Zena-Blockchain

Added view modifiers because it was difficult to check the address and owner of the proxy on the etherscan site.

**Description**

**Tests**

**Invariants**

**Additional context**

**Metadata**

2023-01-13 03:30 UTC, tynes commented
This allows for function selector clashing

2023-01-13 14:54 UTC, maurelian commented
@Zena-Blockchain this is a product decision. We'll evaluate.

2023-01-13 15:24 UTC, smartcontracts commented
Note also that this modifies a contract that would not be modifiable on mainnet, meaning we would have a diff between the ABI in our contracts and the ABI deployed on mainnet.

2023-01-13 16:20 UTC, tynes requested changes
I think that etherscan should have a special field for pulling the eip1967 slots and rendering the values directly instead of us needing to lessen the security model for etherscan

2023-01-17 17:26 UTC, tynes commented
Closing this as it is an etherscan issue

2023-01-17 17:26 UTC, closed without merging