op-batcher: Handle L2 Reorgs better
ethereum-optimism/optimism pull request #4907
Opened 2023-02-16 21:47 UTC by trianglesphere

**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Invariants**

For changes to critical code paths, please list and describe the invariants or key security properties of your new or changed code.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**
- Fixes CLI-3326

2023-02-21 21:29 UTC, sebastianst requested changes

2023-02-21 21:29 UTC, sebastianst commented on op-batcher/batcher/driver.go
> +	// Ensure that the last stored block is still canonical. Not we need this check in addition to the internal check inside the batch
nit:
```suggestion
	// Ensure that the last stored block is still canonical. Note that we need this check in addition to the internal check inside the batch
```

2023-02-21 21:29 UTC, sebastianst commented on op-batcher/batcher/driver.go
> +		l.log.Info("Failed to check if the last stored block is canonical", "err", err)
If this query fails, I suggest we `log.Warn` and also return the error directly.
```suggestion
	if block, err := l.L2Client.BlockByNumber(childCtx, new(big.Int).SetUint64(l.lastStoredBlock.Number)); err != nil {
		l.log.Warn("Failed to check if the last stored block is canonical", "err", err, "number", l.lastStoredBlock.Number)
		return eth.BlockID{}, eth.BlockID{}, fmt.Errorf("checking canonical last stored block: %w", err)
```
The next step is querying the blocks on the L2 client, which then probably also fails. Just returning an error here gives the L2 client time to come back online in the next loop tick.

2023-02-21 21:29 UTC, sebastianst commented on op-batcher/batcher/driver.go
> +		l.log.Warn("Disccovered that the last stored block is no long canonical (L2 reorg occurred)", "number", block.NumberU64(), "last_hash", l.lastStoredBlock.Hash, "new_hash", block.Hash())
nit
```suggestion
		l.log.Warn("Disccovered that the last stored block is no longer canonical (L2 reorg occurred)", "number", block.NumberU64(), "last_hash", l.lastStoredBlock.Hash, "new_hash", block.Hash())
```

2023-02-21 21:29 UTC, sebastianst commented on op-batcher/batcher/driver.go
> +		l.log.Warn("Found L2 reorg", "err", err)
nit: now also include `err` variable in `log.Warn` in loop below, as is done here

2023-02-21 21:49 UTC, sebastianst commented
nevermind, just realized that the root cause of this not working is not found yet.

2023-03-01 22:08 UTC, sebastianst requested changes

2023-03-01 22:08 UTC, sebastianst commented on op-batcher/batcher/channel_manager_test.go
> +
I suggest we add a second check here to make sure it's drained, like
```suggestion
_, _, err = m.TxData(eth.BlockID{})
	require.ErrorIs(t, err, io.EOF)
```

2023-03-01 22:47 UTC, sebastianst approved these changes
lgtm

2023-03-02 16:24 UTC, mslipper approved these changes

2023-03-02 20:49 UTC, merged