op-node: support shanghai L1 blockhash input verification
ethereum-optimism/optimism pull request #5144
Opened 2023-03-14 23:47 UTC by protolambda

**Description**

The Shapella (Shanghai + Capella) L1 network upgrade introduced a breaking change in the L1 block header format the op-node input-validation was not accounting for yet.
This updates the L1 RPC decoding to pull the withdrawals-root from the json, pass it to the geth header type, and verify the block-hash in a Shanghai-compatible way.

Without this fix, the `--l1.trustrpc` flag is required, or the L1 RPC responses will not be accepted due to the unrecognized input data.

Implementers note: the inclusion of the withdrawals-root is not verified against the L1 time, as that would require L1 chain configuration. Instead it includes it if the data is there, and not if it is not there. It affects the block-hash, so verification is still safe even with a bad L1 RPC, as it can be distinguished from the canonical L1 chain.

**Tests**

Minor test framework change: Update the action-test L1-miner actor to include Shapella data into test L1 blocks.

Test: run through a L1 chain that forks into Shanghai, with a verifier and sequencer. The actors use the standard client bindings and derivation code. Both pre and post Shanghai L1 headers will be traversed through by the verifier, and the L2 chain has L1 origins pointing to pre and post Shanghai L1 blocks.

**Invariants**

Accept post-Shanghai L1 block headers as input.

2023-03-14 23:55 UTC, trianglesphere requested changes
rpcHeader fix lgtm, but instead of making an action test can we make unit tests which de-serializes the json of a pre & post shapella block & then verifies the block hash?
This is a very simple deterministic calculation that is well suited to unit testing.

2023-03-14 23:55 UTC, trianglesphere commented on op-node/sources/types.go
> +	WithdrawalsRoot *common.Hash `json:"withdrawalsRoot" rlp:"optional"`
Do we every RLP encode or decode this struct? I know we already have the rlp tags, but I don't think we need them.

2023-03-14 23:55 UTC, tynes commented
If shanghai is turned on at genesis in op-geth, do we need to make any changes there?

2023-03-15 00:25 UTC, trianglesphere approved these changes
lgtm

2023-03-15 18:02 UTC, tynes approved these changes

2023-03-15 19:30 UTC, protolambda commented
rebased on develop

2023-03-15 20:33 UTC, merged