fix(sdk): automatically create std/ETH bridges
ethereum-optimism/optimism pull request #5208
Opened 2023-03-20 20:06 UTC by smartcontracts

**Description**
Updates the SDK to automatically create the Standard and ETH bridges as long as the L1StandardBridge provider is supplied.

2023-03-20 20:09 UTC, roninjin10 approved these changes

2023-03-20 20:09 UTC, roninjin10 commented on packages/sdk/src/utils/contracts.ts
> +              opts?.contracts?.l1?.L1StandardBridge ||
```suggestion
              opts?.contracts?.l1?.L1StandardBridge ??
```
nit.  not at all important in this case just one of those random things I can't help but nit about

2023-03-20 20:09 UTC, roninjin10 commented on packages/sdk/src/utils/contracts.ts
> +              opts?.contracts?.l1?.L1StandardBridge ||
```suggestion
              opts?.contracts?.l1?.L1StandardBridge ??
```
nit

2023-03-20 20:30 UTC, tynes commented
This code is bouncy

2023-03-21 01:53 UTC, tynes approved these changes

2023-03-21 01:54 UTC, tynes requested changes
Actually, this looks like its breaking something now

```
  1) Basic L1<>L2 Communication
       "before all" hook in "Basic L1<>L2 Communication":
     Error: Invalid address
      at assert (/opt/optimism/packages/sdk/src/utils/assert.ts:3:11)
      at toAddress (/opt/optimism/packages/sdk/src/utils/coercion.ts:106:11)
      at new StandardBridgeAdapter (/opt/optimism/packages/sdk/src/adapters/standard-bridge.ts:52:16)
      at getBridgeAdapters (/opt/optimism/packages/sdk/src/utils/contracts.ts:192:28)
      at new CrossChainMessenger (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:176:37)
```

2023-03-21 18:11 UTC, smartcontracts commented
> Actually, this looks like its breaking something now
> 
> ```
>   1) Basic L1<>L2 Communication
>        "before all" hook in "Basic L1<>L2 Communication":
>      Error: Invalid address
>       at assert (/opt/optimism/packages/sdk/src/utils/assert.ts:3:11)
>       at toAddress (/opt/optimism/packages/sdk/src/utils/coercion.ts:106:11)
>       at new StandardBridgeAdapter (/opt/optimism/packages/sdk/src/adapters/standard-bridge.ts:52:16)
>       at getBridgeAdapters (/opt/optimism/packages/sdk/src/utils/contracts.ts:192:28)
>       at new CrossChainMessenger (/opt/optimism/packages/sdk/src/cross-chain-messenger.ts:176:37)
> ```

Fixed ser

2023-03-21 18:33 UTC, merged