feat(ctb): Move updateDynamicConfig before phase2 steps
ethereum-optimism/optimism pull request #5377
Opened 2023-04-06 19:51 UTC by maurelian

2023-04-06 19:52 UTC, maurelian commented
Current dependencies on/for this PR:
* develop
  * **PR #5359** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/5359" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #5377** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/5377" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/5377?utm_source=stack-comment).

2023-05-01 15:25 UTC, refcell requested changes
Small changes otherwise lgtm pending ci fixes

2023-05-01 15:25 UTC, refcell commented on packages/contracts-bedrock/contracts/deployment/SystemDictator.sol
> +     * @notice Calls the next remaings steps of the migration process.
```suggestion
     * @notice Calls the remaining steps of the migration process.
```

2023-05-01 15:27 UTC, clabby reviewed
LGTM, will approve once linting is fixed and the `L1ERC721Bridge` check is added.

2023-05-01 15:27 UTC, clabby commented on packages/contracts-bedrock/deploy/021-SystemDictatorSteps-2.ts
> +
Should probably add a check for the ownership of the `L1ERC721Bridge` here as well.

2023-05-01 16:35 UTC, clabby approved these changes
lgtm

2023-05-01 16:54 UTC, refcell approved these changes

2023-05-01 18:19 UTC, merged