maint(core): clean up test folder structure
ethereum-optimism/optimism pull request #5382
Opened 2023-04-06 22:32 UTC by smartcontracts

**Description**
Small PR to clean up the folder structure for the tests for core-utils so that the folders follow the source folders and file names. Planning to make some improvements to these tests, this is a first simple PR that will help me do that.

2023-04-06 22:54 UTC, roninjin10 requested changes

2023-04-06 22:54 UTC, roninjin10 commented on packages/core-utils/package.json
> +    "test": "ts-mocha test/**/*.spec.ts",
Update test:coverage below too

2023-04-07 18:51 UTC, smartcontracts commented on packages/core-utils/package.json
> +    "test": "ts-mocha test/**/*.spec.ts",
Done

2023-04-07 19:04 UTC, roninjin10 approved these changes

2023-04-10 20:23 UTC, tynes approved these changes

2023-04-11 01:49 UTC, merged