op-node: L1BlockInfo MarshalBinary&UnmarshalBinary migrated to writer…
ethereum-optimism/optimism pull request #5400
Opened 2023-04-10 09:28 UTC by Nickqiaoo

Description:

L1BlockInfo MarshalBinary&UnmarshalBinary migrated to writer&reader based API

Metadata

Fixes #5358

2023-04-10 11:25 UTC, Nickqiaoo commented
Hi, this is my first PR,  I really hope to contribute code to optimism.😊

2023-04-10 17:44 UTC, trianglesphere requested changes
Thanks for picking this up. There's a couple small things, but overall it's the right direction.

2023-04-10 17:44 UTC, trianglesphere commented on op-node/rollup/derive/l1_block_info.go
> +	if _, err := reader.Read(readPadding[:]); err != nil || !bytes.Equal(readPadding[:], padding[:]) {
Can use [io.ReadFull](https://pkg.go.dev/io#ReadFull) here to ensure that it reads enough.

2023-04-10 17:44 UTC, trianglesphere commented on op-node/rollup/derive/l1_block_info.go
> +	if _, err := reader.Read(info.BatcherAddr[:]); err != nil {
Should also use `ReadFull` to ensure that the array is completely filled

2023-04-10 17:44 UTC, trianglesphere commented on op-node/rollup/derive/l1_block_info.go
> +//| 24      | Padding for Number       |
These padding + number pairs are a good candidate to be pulled out into a single read/write function (like `readSolidityABIUint64`)

2023-04-12 23:17 UTC, trianglesphere commented on op-node/rollup/derive/l1_block_info.go
> +	writeSolidityABIUint64 := func(num uint64) {
This can be a standalone function. API like `func writeSolidityABIUint64(w io.Writer, num uint64)`

2023-04-12 23:17 UTC, trianglesphere commented on op-node/rollup/derive/l1_block_info.go
> +	readSolidityABIUint64 := func() (num uint64, err error) {
Ditto standalone function

2023-04-12 23:17 UTC, trianglesphere commented on op-node/rollup/derive/l1_block_info.go
> +func (info *L1BlockInfo) UnmarshalBinary(data []byte) (err error) {
We prefer explicit returns, particularly when we don't need to differentiate the different return values.

2023-04-14 19:24 UTC, trianglesphere approved these changes
tyvm

2023-04-14 19:32 UTC, merged