fix: error log content in func FindL2Heads
ethereum-optimism/optimism pull request #5454
Opened 2023-04-14 10:06 UTC by nolanxyg

**Description**

fix error log content in func FindL2Heads

**Tests**

no need

**Invariants**

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

**TODOs**

- [ ] Author or reviewer has added an entry to the [current release notes draft][RND], if appropriate.

[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be14e7c984953&pvs=4 "Release Notes"

2023-04-14 15:04 UTC, tynes approved these changes

2023-04-14 15:37 UTC, trianglesphere reviewed
Really nice find. I think this error actually occurred multiple other times in the file.

2023-04-14 15:38 UTC, trianglesphere requested changes
Really nice find. I think this error actually occurred multiple other times in the file.

2023-04-15 03:49 UTC, nolanxyg commented
> Really nice find. I think this error actually occurred multiple other times in the file.

true, found another error, thanks for remind.

2023-04-17 17:56 UTC, trianglesphere approved these changes
tyvm

2023-04-17 17:56 UTC, merged