contracts-bedrock: update constructor require statment
ethereum-optimism/optimism pull request #5478
Opened 2023-04-17 22:04 UTC by tynes

**Description**

Updates the constructor check in the `L2OutputOracle` so that it is correct. It previously compared two different types of units (blocknumbers and timestamps). The real thing that we need to ensure is that neither is 0 because that will result in a broken system.

2023-04-17 22:33 UTC, refcell approved these changes
Nice! Looks good to me!

2023-04-17 22:41 UTC, refcell approved these changes
Small natspec semver bump, otherwise looks good!

2023-04-17 22:41 UTC, refcell commented on packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol
> +    ) Semver(1, 3, 0) {
The natspec above uses `1.2.0` - should bump that as well to `1.3.0`

2023-04-17 23:54 UTC, maurelian approved these changes
LGTM assuming resolution of the semver in natspec

2023-04-18 00:40 UTC, clabby requested changes
LGTM- will approve once the natspec comment above the constructor has been updated from `1.2.0` -> 1.3.0`

2023-04-18 13:58 UTC, tynes commented
I've updated the natspec, good call on that. Its very easy to forget to update the natspec tag when updating the version, i wonder if there is a better way to manage this.

2023-04-18 20:38 UTC, maurelian commented
> Its very easy to forget to update the natspec tag when updating the version, i wonder if there is a better way to manage this.

@tynes do we really need the tag?

2023-04-18 20:51 UTC, refcell commented
> > Its very easy to forget to update the natspec tag when updating the version, i wonder if there is a better way to manage this.
> 
> @tynes do we really need the tag?

Maybe split semver tags into a gardening ticket to explore enforcing a version bump if the file is changed?

2023-04-18 21:39 UTC, tynes commented
> > Its very easy to forget to update the natspec tag when updating the version, i wonder if there is a better way to manage this.
> 
> @tynes do we really need the tag?

We are supposed to do a patch semver for any change to the source that doesn't change the bytecode

2023-04-19 00:21 UTC, clabby approved these changes

2023-04-19 02:02 UTC, merged