feat(sdk): add custom bridge address for ECO
ethereum-optimism/optimism pull request #5695
Opened 2023-05-11 23:48 UTC by jakim929

2023-05-11 23:49 UTC, jakim929 commented
Current dependencies on/for this PR:
* develop
  * **PR #5695** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/5695" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/5695?utm_source=stack-comment).

2023-05-13 02:12 UTC, roninjin10 requested changes
Can we add a vitest test?   I can help pair on it

2023-05-18 19:26 UTC, roninjin10 commented on packages/sdk/test-next/testUtils/viemClients.ts
> +import { goerli, optimismGoerli } from 'viem/chains'
I might make this it's own package later

2023-05-18 19:31 UTC, roninjin10 approved these changes

2023-05-18 19:31 UTC, roninjin10 commented on packages/sdk/package.json
> +    "test:next": "vitest run",
```suggestion
    "test:next": "vitest",
    "test:next:run": "vitest run",
```

2023-05-18 20:52 UTC, twoshark approved these changes

2023-05-18 21:44 UTC, merged