feat(ctb): Copy goerli Lib_AddressManager deployment to bedrock
ethereum-optimism/optimism pull request #5853
Opened 2023-06-01 16:59 UTC by maurelian

**Description**

This change ensures that we're handling deployment artifacts the same between Goerli and Mainnet.

Will make it easier to delete the legacy contracts package in the future as well.

2023-06-01 17:20 UTC, tynes requested changes
Can we rename to `AddressManager.json` to be 1:1 with mainnet? The go tooling will break otherwise because duplicate file name

2023-06-01 20:59 UTC, tynes commented
We still need to delete the old file with the old name, then LGTM

2023-06-02 13:17 UTC, maurelian commented
OK. Changes this around so that it: 
1. Uses the new name
2. Copies the file instead of moving it (I think that might've broken something in the legacy package).

2023-06-08 16:12 UTC, tynes approved these changes

2023-06-08 17:03 UTC, merged