dtl: remove legacy encoding
ethereum-optimism/optimism pull request #618
Opened 2021-04-24 01:44 UTC by tynes

**Description**
Removes the legacy decoding because it is no longer needed post regenesis

2021-04-26 16:59 UTC, annieke requested changes
these unit tests can now be removed! https://github.com/ethereum-optimism/optimism/blob/1ae59c64fe60b7742807a984e7e759ac372c1e6a/packages/data-transport-layer/test/unit-tests/services/l1-ingestion/handlers/sequencer-batch-appended.spec.ts#L181-L196

2021-04-27 00:30 UTC, karlfloersch approved these changes
LGTM!

2021-04-27 00:31 UTC, snario approved these changes

2021-04-27 00:32 UTC, snario commented
Removes the need for one of the metrics mentioned in #636

2021-04-27 00:34 UTC, merged