fix(ctb): MIPS Styling and Docs
ethereum-optimism/optimism pull request #6276
Opened 2023-07-12 18:57 UTC by refcell

**Description**

Stylizes MIPS.sol and adds some documentation in the form of inline comments.

2023-07-12 18:58 UTC, refcell commented
Current dependencies on/for this PR:
* develop
  * **PR #6269** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/6269" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #6270** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/6270" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #6276** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/6276" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/6276?utm_source=stack-comment).

2023-07-14 18:03 UTC, clabby requested changes
LGTM; There is an odd mix of 2 spaces / 4 spaces indentation. LGTM after that's fixed :)

2023-07-14 18:03 UTC, clabby commented on packages/contracts-bedrock/contracts/cannon/MIPS.sol
> +        }
Tabs look to have been messed up here

2023-07-14 18:25 UTC, clabby approved these changes
👑 

g2g once CI passes.

2023-07-14 18:39 UTC, merged