contracts-bedrock: erc721 bridge single impl
ethereum-optimism/optimism pull request #6477
Opened 2023-07-27 05:42 UTC by tynes

**Description**

Update the ERC721 bridge so that a single implementation
can be used across many different chains.

Still need to double check the storage layout before this
is good, but the tests are passing.

Also need to update all the code that touches the go bindings.

2023-08-04 02:00 UTC, tynes commented
This still needs some fixing up

2023-08-08 14:57 UTC, refcell requested changes
Looks good, just one small nit.

**Checks**

Checked L2 Output
```
INFO [08-08|10:47:27.930] L2ERC721Bridge                           implementation=0xC0D3c0d3c0d3c0d3c0D3C0d3C0D3C0D3c0d30014
INFO [08-08|10:47:27.932] L2ERC721Bridge                           MESSENGER=0x4200000000000000000000000000000000000007
INFO [08-08|10:47:27.932] L2ERC721Bridge                           OTHERBRIDGE=0xb2Db8a261CD2c462E3b9548324D5dACf2B7a5687
INFO [08-08|10:47:27.933] L2ERC721Bridge version                   version=1.3.0
```

Implementation messenger correctly zeroed in the devnet
```sh
$ cast call 0xC0D3c0d3c0d3c0d3c0D3C0d3C0D3C0D3c0d30014 \
    "messenger()" \
    --rpc-url http://127.0.0.1:9545
0x0000000000000000000000000000000000000000000000000000000000000000
```

Proxy messenger set correctly
```sh
$ cast call 0x4200000000000000000000000000000000000014 \
    "messenger()" \
    --rpc-url http://127.0.0.1:9545
0x0000000000000000000000004200000000000000000000000000000000000007
```

2023-08-08 14:57 UTC, refcell commented on packages/contracts-bedrock/test/L2ERC721Bridge.t.sol
> +import { Proxy } from "../src/universal/Proxy.sol";
This doesn't seem used.
```suggestion
```

2023-08-08 15:14 UTC, tynes commented on packages/contracts-bedrock/test/L2ERC721Bridge.t.sol
> +import { Proxy } from "../src/universal/Proxy.sol";
Good catch, fixed, thank you

2023-08-08 16:30 UTC, Inphi reviewed
looks good. one nit on contract semvers

2023-08-08 16:30 UTC, Inphi commented on packages/contracts-bedrock/src/L1/L1ERC721Bridge.sol
> +    constructor() Semver(1, 3, 0) ERC721Bridge(Predeploys.L2_ERC721_BRIDGE) {
why skip 1.2.0; 1.1.2 -> 1.3.0?

2023-08-08 17:01 UTC, tynes commented on packages/contracts-bedrock/src/L1/L1ERC721Bridge.sol
> +    constructor() Semver(1, 3, 0) ERC721Bridge(Predeploys.L2_ERC721_BRIDGE) {
Good call

2023-08-08 18:56 UTC, tynes commented
I've addressed all comments on this PR and believe its ready to be merged

2023-08-08 19:25 UTC, refcell approved these changes
Looks good now 🎉

2023-08-08 19:29 UTC, clabby approved these changes
LGTM

2023-08-08 19:31 UTC, clabby requested changes

2023-08-08 19:31 UTC, clabby commented on packages/contracts-bedrock/src/L2/L2ERC721Bridge.sol
> +    /// @custom:semver 1.3.0
nit: This should be bumped to `1.2.0`

2023-08-08 19:40 UTC, clabby approved these changes

2023-08-08 19:40 UTC, tynes commented
@clabby addressed your comment

2023-08-08 19:55 UTC, merged