feat: enable L2OutputOracle impl usage by multiple proxies
ethereum-optimism/optimism pull request #6566
Opened 2023-08-02 18:55 UTC by tynes

**Description**

Allows for the `L2OutputOracle` to be usable by multiple proxies and update the ABI in a backwards compatible way.

- The storage layout is not altered, only updated
- `reinitializer(2)` allows for the same proxy to be initialized again, this number must increment

2023-08-02 19:46 UTC, tynes commented on packages/contracts-bedrock/test/L2OutputOracle.t.sol
> +    /* For some reason, this test causes foundry to stack overflow
Will come back to this

2023-08-02 19:50 UTC, tynes commented on packages/contracts-bedrock/src/L1/L2OutputOracle.sol
> +
These can technically have their style changed now

2023-08-07 21:06 UTC, refcell requested changes
Couple of comments and nits, otherwise looks good. Nice catch on the chain-mon helper update.

2023-08-07 21:06 UTC, refcell commented on op-proposer/proposer/abi_test.go
> +	)
I don't think this is correct. The constructor of the `L2OutputOracle` changed to accept args like so:
```diff
        uint256 _submissionInterval,
        uint256 _l2BlockTime,
-       uint256 _startingBlockNumber,
-       uint256 _startingTimestamp,
-       address _proposer,
-       address _challenger,
        uint256 _finalizationPeriodSeconds
```

So, I believe this should be:
```suggestion
		big.NewInt(10),
		big.NewInt(2),
		big.NewInt(100))
	)
```

2023-08-07 21:06 UTC, refcell commented on packages/contracts-bedrock/test/L2OutputOracle.t.sol
> +    function test_constructor_badTimestamp_reverts() external {
nit
```suggestion
    /// @dev Tests that the initialize function reverts if the starting timestamp is invalid.
    function test_initialize_badTimestamp_reverts() external {
```

2023-08-07 21:41 UTC, tynes commented on op-proposer/proposer/abi_test.go
> +	)
Great catch here

2023-08-07 22:09 UTC, refcell approved these changes

2023-08-07 22:13 UTC, mslipper approved these changes

2023-08-08 01:17 UTC, merged