feat: forge fmt
ethereum-optimism/optimism pull request #6651
Opened 2023-08-09 04:19 UTC by tynes

**Description**

Migrate to `forge fmt` for linting

2023-08-09 14:14 UTC, maurelian commented
Any thoughts as to why the bindings are modified?

2023-08-09 14:47 UTC, tynes commented
> Any thoughts as to why the bindings are modified?

WETH9 has a 32 byte diff which is likely the source hash. The others have a patch semver bump

There isn't a good way to exclude contracts using `forge fmt` atm, otherwise I would ignore weth

2023-08-09 15:20 UTC, tynes commented
I just rebased this PR, would like to get it in sooner rather than later

2023-08-09 16:50 UTC, tynes commented
h/t @clabby for showing how to ignore files with `forge fmt`, now ignoring `weth9` cc @maurelian

2023-08-09 17:00 UTC, maurelian approved these changes
LGTM. 
My review mechanism was as follows: 
1. verify that formatting changes only occurred in a single commit: 38d8fcc5b1bd05bbb95d609aa533268a8b724828
2. checkout that commit, rebuild bindings, and verify that the bytecode was unchanged. 
3. verify that the only other changes to implementation code in other commits were semver bumps.

Thus we can be confident that the formatting changes do not modify logic.

2023-08-09 17:05 UTC, tynes commented
Gas snapshot modified by semver changes

2023-08-09 19:36 UTC, refcell requested changes
Big pr; long review here.
Mostly nits
Some important changes
Many can probably be dismissed
Discussion offline expected to push this over the line.

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/scripts/Deployer.sol
>      ///         once with different versions of the compiler.
nit
```suggestion
    /// @notice Removes the semantic versioning from a contract name. The semver will exist if the contract is compiled
    /// more than once with different versions of the compiler.
```

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/EAS/SchemaRegistry.sol
> +    constructor() Semver(1, 0, 2) { }
Why did this update?

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/EAS/resolver/SchemaResolver.sol
>      ///        in the batch.
nit fix
```suggestion
    ///        both attest() and multiAttest() callbacks EAS-only callbacks and that in case of multi attestations,
    ///        it'll usually hold that msg.value != value, since msg.value aggregated the sent ETH amounts for all
    ///        the attestations in the batch.
```

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/EAS/resolver/SchemaResolver.sol
>      ///        in the batch.
nit fix
```suggestion
    ///        both revoke() and multiRevoke() callbacks EAS-only callbacks and that in case of multi attestations,
    ///        it'll usually hold that msg.value != value, since msg.value aggregated the sent ETH amounts for all
    ///        the attestations in the batch.
```

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol
> +    constructor() Semver(1, 5, 1) CrossDomainMessenger(Predeploys.L2_CROSS_DOMAIN_MESSENGER) {
Do these need to update?

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/L1/ResourceMetering.sol
>      // solhint-disable-next-line func-name-mixedcase
We removed solhint so this should be removable right?
```suggestion
```

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/cannon/MIPS.sol
> +                    // 32*3+4=100 expected state data offset
nit, now that we follow formatting, let's make comment algebra properly spaced
```suggestion
                    // 32 * 3 + 4 = 100 expected state data offset
```

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/cannon/MIPS.sol
> +                    // 100+32+256=388 expected proof offset
ibid nit
```suggestion
                    // 100 + 32 + 256 = 388 expected proof offset
```

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/cannon/MIPS.sol
> +                    else if (opcode == 0xe) func = 0x26; // xori
NOTE: feel free to dismiss this comment... leaving as a note for @refcell 

todo(@refcell): track via a github issue to upstream fix to foundry

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol
>      /// @notice constructs a new DisputeGameFactory contract.
Looks like we're missing a semver natspec comment here.
```suggestion
    /// @custom:semver 0.0.4
    /// @notice constructs a new DisputeGameFactory contract.
```

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol
> +        Semver(0, 0, 8)
Can't leave a review on the comment above but it's not updated to the changed `0.0.8` semver.
ie, this
`    /// @custom:semver 0.0.7`
should be
`    /// @custom:semver 0.0.8`
above the constructor.

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/legacy/L1BlockNumber.sol
> +    constructor() Semver(1, 0, 2) { }
This contract doesn't look like it has any source changes - no semver bump?
```suggestion
    /// @custom:semver 1.0.1
    constructor() Semver(1, 0, 1) {}
```

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/legacy/LegacyMessagePasser.sol
> +    constructor() Semver(1, 0, 2) { }
This contract doesn't look like it has any source changes - no semver bump?
```suggestion
    /// @custom:semver 1.0.1
    constructor() Semver(1, 0, 1) {}
```

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/periphery/op-nft/AttestationStation.sol
> +    constructor() Semver(1, 1, 1) { }
This should be bumped
```suggestion
    /// @custom:semver 1.1.2
    constructor() Semver(1, 1, 2) { }
```

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/periphery/op-nft/Optimist.sol
> +        Semver(2, 0, 1)
This and the natspec tag above should be bumped.
```suggestion
        Semver(2, 0, 2)
````

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/periphery/op-nft/OptimistAllowlist.sol
> +        Semver(1, 0, 1)
This and the natspec tag above should be bumped.
```suggestion
        Semver(1, 0, 2)
````

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/periphery/op-nft/OptimistInviter.sol
>      /// @param _inviteCount Number of invites to set to.
semver and its natspec tag above should be bumped.

2023-08-09 19:36 UTC, refcell commented on packages/contracts-bedrock/src/universal/OptimismMintableERC20.sol
> +        Semver(1, 0, 2)
This and the natspec tag above should be bumped.
```suggestion
        Semver(1, 0, 3)
````

2023-08-10 00:17 UTC, tynes commented on packages/contracts-bedrock/src/EAS/SchemaRegistry.sol
> +    constructor() Semver(1, 0, 2) { }
This updated because the source code changed? Can you clarify your question?

2023-08-10 00:20 UTC, tynes commented on packages/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol
> +    constructor() Semver(1, 5, 1) CrossDomainMessenger(Predeploys.L2_CROSS_DOMAIN_MESSENGER) {
I mean I suppose they just changed but might as well to follow the rules

2023-08-10 00:53 UTC, refcell commented on packages/contracts-bedrock/src/EAS/SchemaRegistry.sol
> +    constructor() Semver(1, 0, 2) { }
Disregard - my oversight

2023-08-10 01:01 UTC, refcell approved these changes
**L**ord **G**ive **T**ynes **M**oney.

2023-08-10 02:13 UTC, refcell approved these changes

2023-08-10 02:28 UTC, merged