Airdrop 2 Onion Cli
ethereum-optimism/optimism pull request #7217
Opened 2023-09-12 23:31 UTC by spacesailor24

This CLI was originally created by Mark, but @tremarkley and I have extended it to allow for filtering of sanctioned addresses and to output a filtered CSV file if needed

2023-09-12 23:41 UTC, tremarkley approved these changes

2023-09-12 23:41 UTC, tremarkley commented on packages/contracts-bedrock/.env.example
> +SAVE_DESTINATION="/absolute/path/to/non-sanctioned-addresses.txt"
maybe we should prefix all of these with `ONION_` since they are specific to the onion cli?

2023-09-13 00:31 UTC, tynes commented
We are trying to keep minimal js deps in contacts bedrock so please put this in another package or keep it someplace outside of the monorepo as I don't believe it'll be used long term

2023-09-13 00:45 UTC, nickbalestra requested changes
Agree with @tynes , Can we move this to its own repo, so that we have the code somewhere for future reference, but no need to have this within the optimism monorepo.

2023-09-13 01:11 UTC, closed without merging