fix(hh-ovm): Working compilation for M1 macs
ethereum-optimism/optimism pull request #751
Opened 2021-05-04 21:54 UTC by ben-chain

**Description**
Fixes the long-elusive https://github.com/ethereum-optimism/optimism/issues/675 where builds were failing on M1 macs.  There is a better fix for this long-term, but we should merge this in now to unblock M1 users.

**Additional context**
We barked up the wrong tree on this one for a while because it looked an awful lot like a caching issue, but turned out to be something else: it seems that on M1s, the hardhat `TASK_COMPILE_SOLIDITY_RUN_SOLC` does not run, probably because it does not see an M1 build, and therefore wants `TASK_COMPILE_SOLIDITY_RUN_SOLCJS` to be run directly.  The fix here routes this task back to `TASK_COMPILE_SOLIDITY_RUN_SOLC` on the first pass, because `hh-ovm` already enforces that we run solcjs, and within that task we do the `//  @unsupported: evm/ovm` filtering.

**Metadata**
- Fixes #675

2021-05-04 22:48 UTC, tynes requested changes
This needs a changeset and a repro that works from somebody with a M1

2021-05-04 23:16 UTC, ben-chain commented
> This needs a changeset and a repro that it works from somebody with a M1

I was able to repro the bug on my own M1 which is where I fixed it, so I think those are both covered now :)

2021-05-05 00:03 UTC, TransmissionsDev commented
Confirmed working on my M1. Didn't even see the address manager bug!

2021-05-05 01:33 UTC, tynes approved these changes

2021-05-05 01:34 UTC, merged