feat: Migrate branch from develop to main
ethereum-optimism/optimism pull request #8034
Opened 2023-11-03 15:58 UTC by roninjin10

We currently have a single branch model but that single branch for historical reasons is develop. This migrates the single branch to main. I chose main over master because main is 4 letters to type and master is 6. The ethereum-optimism org is pretty inconsistent here in general we have many repos with main and others with master.

This pr depends on the following
- [ ] Need to create a main branch in the repo
- [ ] Need to change the repo settings to point to main. @mslipper or someone with permissions needs to do this

Note: Because we are changing repo settings this is not a trivial thing to revert. We need to be very careful about this and thus I'm putting a do-not-merge tag on this pr until we decide the best time to pull the trigger here. This pr could very easily disrupt workflows

## Open questions

- [ ] Do any third party services depend on master or develop branch? E.g. are there any netlify apps currently pointing at these branches

2023-11-03 17:56 UTC, sebastianst requested changes
Thanks so much for driving this forward! ✨ Left a few comments.

* We should seize the opportunity to clean up and simplify the "Branching Model" section of the README. It already wasn't very accurate as of late, but with this change to a single `main` branch, many info in there, even whole subsections, don't make sense any more.
* There are a lot of substitutions in `packages/contracts-bedrock/deployments`, not sure if they were intended.
* In general, there seem to have been a few substitutions of `master` and `develop` with `main` that probably weren't intended. I left comments where I noticed this.

2023-11-03 17:56 UTC, sebastianst commented on README.md
> +Please refer to the canonical [Security Policy](https://github.com/ethereum-optimism/.github/blob/main/SECURITY.md) document for detailed information about how to report vulnerabilities in this codeb
This link refers to the `.github` repo, which only has a `master` branch rn

2023-11-03 17:56 UTC, sebastianst commented on README.md
> +| release/X.X.X                                                                          | Accepts PRs for all changes, particularly those not backwards compatible with `main` and `main`. |
We can clean up this whole section to say that we develop on a single `main` branch.

2023-11-03 17:56 UTC, sebastianst commented on README.md
> +Updates from `main` **always** come from the `main` branch.
We could probably just delete this section. The last line now mentions `main` twice and lost its meaning.

2023-11-03 17:56 UTC, sebastianst commented on SECURITY.md
> +Please see our security policy document [here](https://github.com/ethereum-optimism/.github/blob/main/SECURITY.md).
again, `.github` repo has a single `master` branch.

2023-11-03 17:56 UTC, sebastianst commented on docs/fault-proof-alpha/immunefi.md
> +For the Fault Proof Alpha security review, we've pinned `546fb2c7a5796b7fe50b0b7edc7666d3bd281d6f` as the commit hash in the monorepo. This commit hash was the head of the `main` branch at the time o
In this sentence it might make more sense to keep saying `develop`.

2023-11-03 17:56 UTC, sebastianst commented on docs/postmortems/2022-02-02-inflation-vuln.md
> +[Security Policies page](https://github.com/ethereum-optimism/.github/blob/main/SECURITY.md).
`.github` repo

2023-11-03 17:56 UTC, sebastianst commented on ops/check-changed/main.py
> +    'main'
duplicate now

2023-11-03 17:56 UTC, sebastianst commented on ops/docker/ci-builder/Dockerfile
> +  curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/main/install.sh | bash; \
different repo

2023-11-03 17:56 UTC, sebastianst commented on packages/contracts-bedrock/CONTRIBUTING.md
> +**Any and all bug reports on production smart contract code should be submitted privately to the Optimism team so that we can mitigate the issue before it is exploited. Please see our security policy
`.github` repo

2023-11-03 17:56 UTC, sebastianst commented on packages/contracts-bedrock/STYLE_GUIDE.md
> +Optimism smart contracts follow the triple-slash [solidity natspec comment style](https://docs.soliditylang.org/en/main/natspec-format.html#documentation-example)
different repo

2023-11-03 17:56 UTC, sebastianst commented on packages/contracts-bedrock/src/cannon/MIPS.sol
> +/// @dev https://github.com/golang/go/blob/main/src/syscall/zerrors_linux_mips.go
different repo

2023-11-03 17:56 UTC, sebastianst commented on packages/contracts-bedrock/src/vendor/WETH9.sol
> +  If you main a new program, and you want it to be of the greatest
shouldn't be replaced.

2023-11-03 17:56 UTC, sebastianst commented on packages/contracts-bedrock/test/mocks/TestERC1271Wallet.sol
> +///         blob/main/contracts/mocks/ERC1271WalletMock.sol
different repo

2023-11-03 17:56 UTC, sebastianst commented on proxyd/rpc.go
> +	// https://github.com/ethereum/go-ethereum/blob/main/rpc/json.go#L72
different repo

2023-11-03 17:56 UTC, sebastianst commented on specs/exec-engine.md
> +[discv5-rationale]: https://github.com/ethereum/devp2p/blob/main/discv5/discv5-rationale.md
all different repos

2023-11-03 17:56 UTC, sebastianst commented on specs/exec-engine.md
> +[snap-sync]: https://github.com/ethereum/devp2p/blob/main/caps/snap.md
different repo

2023-11-03 17:56 UTC, sebastianst commented on specs/rollup-node-p2p.md
> +[extended-validator]: https://github.com/libp2p/specs/blob/main/pubsub/gossipsub/gossipsub-v1.1.md#extended-validators
all different repos

2023-11-03 17:58 UTC, roninjin10 commented on README.md
> +Please refer to the canonical [Security Policy](https://github.com/ethereum-optimism/.github/blob/main/SECURITY.md) document for detailed information about how to report vulnerabilities in this codeb
tyty will fix bad greps

2023-11-05 21:58 UTC, ajsutton commented
Is there a reason we don't just call our main branch `develop`? The name is arbitrary. We could delete or rename the `master` branch if that's causing confusion.

If we do want to rename the default branch, we should just rename develop rather than creating a new `main`, then GitHub will create redirect links and I think even keep `develop` working as an alias for `main` in the git protocol.  They built it to support renaming from `master` to `main` and it makes renames a lot less painful (though you still inevitably keep finding problems for ages afterwards).

2023-11-05 22:22 UTC, roninjin10 commented
@ajsutton I would actually prefer that. That is main reason I have been dragging feet on this pr. It's something I'd expect most people to want but I don't see any value from changing the branch name and it has non 0 cost/risk

2023-11-05 22:26 UTC, roninjin10 commented
I think if we chose to keep develop we would need to delete master it existing is confusing. Happy to talk about it at both office hours this week or I could make a quick pros/cons doc and get async feedback

2023-11-05 23:52 UTC, ajsutton commented
Yep, I'd be in favour of renaming `master` (not sure to what and I don't really mind just deleting it) and keeping the default branch as `develop`. At least worth seeing if that helps reduce confusion before we go to the effort of renaming develop.

2023-11-16 00:00 UTC, roninjin10 commented
At office hours we decided to try to do this before holiday shutdown at least risky time

2023-11-16 00:00 UTC, closed without merging