contracts-bedrock: Add logs in ChainAssertions to help debugging
ethereum-optimism/optimism pull request #8522
Opened 2023-12-08 04:03 UTC by maurelian

**Description**

A few additional log statements in ChainAssertions.sol to make debugging easier.

2023-12-08 14:29 UTC, clabby requested changes

2023-12-08 14:29 UTC, clabby commented on packages/contracts-bedrock/scripts/ChainAssertions.sol
> +            // require(address(messenger.superchainConfig()) == address(0));
Intentionally left commented out? Should reintroduce or remove these, but it looks like we need them still.

2023-12-08 16:08 UTC, maurelian commented on packages/contracts-bedrock/scripts/ChainAssertions.sol
> +            // require(address(messenger.superchainConfig()) == address(0));
lol whoops

2023-12-15 20:19 UTC, clabby approved these changes

2023-12-15 21:07 UTC, merged