op-node: Remove alt RPC sync
ethereum-optimism/optimism pull request #8593
Opened 2023-12-12 22:41 UTC by trianglesphere

**Description**

The P2P Alt sync protocol has proven it's worth & we no longer need this alternate sync mechanism. Removing it will simplify how prepare for the op-node changes required for snap sync.

2023-12-14 18:31 UTC, mslipper requested changes
Coinbase is actively using this feature - is there a way to preserve this functionality while also retaining compatibility with snap sync?

2023-12-15 18:48 UTC, mslipper approved these changes

2023-12-15 18:48 UTC, mslipper commented
Approved, since Coinbase has a workaround.

2023-12-15 19:27 UTC, merged

2026-01-13 08:00 UTC, ClaudeZsb commented
> Approved, since Coinbase has a workaround.

hi, could I know what's the workaround made by Base? We have a forked bedrock chain relies on this feat and recently thinking about updating the code base to newest op. Then we're facing the dilemma of removing it or working around it. Thanks in advance.