chore: fix typo
ethereum-optimism/optimism pull request #9127
Opened 2024-01-22 14:37 UTC by zhiqiangxu

2024-01-22 16:25 UTC, refcell approved these changes

2024-01-22 16:28 UTC, refcell commented
Hey @zhiqiangxu, thank you for this PR! It looks good but we are moving specs into a dedicated repo (see https://github.com/ethereum-optimism/optimism/pull/9121 which removes the `specs` directory).

Would you mind closing this PR and opening one with these changes in the new specs repo: https://github.com/ethereum-optimism/specs

Thank you!

2024-01-22 16:29 UTC, refcell requested changes
Hey @zhiqiangxu, thank you for this PR! It looks good but we are moving specs into a dedicated repo (see https://github.com/ethereum-optimism/optimism/pull/9121 which removes the `specs` directory).

Would you mind closing this PR and opening one with these changes in the new specs repo: https://github.com/ethereum-optimism/specs

Thank you!

2024-01-23 02:07 UTC, zhiqiangxu commented
Close since already moved to https://github.com/ethereum-optimism/specs/pull/3

2024-01-23 02:07 UTC, closed without merging