feat[ci]: parallelize integration, example, and sync tests
ethereum-optimism/optimism pull request #972
Opened 2021-05-27 20:18 UTC by annieke

**Description**
Make integration testing more efficient by parallelizing the 3 test suites.

**Additional context**
following up on https://github.com/ethereum-optimism/optimism/pull/913

**Metadata**
- OP-810

2021-05-28 00:07 UTC, annieke commented on ops/scripts/save-ci.sh
> +docker images
note: remove this after debugging

2021-05-28 07:50 UTC, gakonst requested changes
The work flows still take many minutes to run because the load-images step is not finding the tarballs

2021-05-31 13:43 UTC, gakonst requested changes
This PR does what we want, but it seems to be making things slower due to having to save/upload & download/load the images...If this does not improve our CI times let's hold on it. I've opened #989 to enable the sync tests on CI.

2021-06-01 13:39 UTC, snario commented
Curious if you considered using the caching strategy Docker proposes [here](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache)?

2021-06-02 01:22 UTC, annieke commented
@snario just poked around some docs and i think for us to share images between jobs (necessary for parallelizing the tests), the uploading artifacts part is still necessary, and the caching just helps with the build part: https://github.com/docker/build-push-action/issues/225 let me know if your investigations yield any further results! going to mark this as draft until then

2021-06-07 21:22 UTC, closed without merging