feat(sdk): Add mode constants
ethereum-optimism/optimism pull request #9973
Opened 2024-03-26 09:29 UTC by raffaele-oplabs

**Description**

In order to have wd-mon to work with MODE MAINNET network I need to add MODE mainnent specific costants values.

In particular changes relate to:
L2ChainID.MODE_MAINNET addresses
L2ChainID.MODE_MAINNET
DEPOSIT_CONFIRMATION_BLOCKS for MODE_MAINNET

**Tests**

 have tested the new sdk locally with the new values on wd-mon

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

2024-03-26 13:42 UTC, mds1 commented on packages/sdk/src/interfaces/types.ts
> +  MODE_MAINNET = 34443,
We should probably also add Mode Sepolia, chain ID 919

2024-03-26 13:45 UTC, mds1 commented on packages/sdk/src/utils/chain-constants.ts
> +  [L2ChainID.MODE_MAINNET]: {
Mode sepolia addresses can be found here: https://github.com/ethereum-optimism/superchain-registry/pull/107/files#diff-eeca29e52df49e42d3e255a7b46c5acf519012a22c85c11c31d3ca9b2478be77

2024-03-26 19:00 UTC, roninjin10 requested changes
Can you add a changeset with `pnpm changeset` for a minor release with a message like `Added support for MODE sepolia and MODE mainnet`

2024-03-27 14:52 UTC, roninjin10 approved these changes

2024-03-27 15:11 UTC, merged